[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; LoRa and Mesh libraries
lib_deps =
    https://github.com/Xinyuan-LilyGO/LilyGO-LoRa-Series.git
    https://github.com/meshtastic/protobufs.git
    https://github.com/sandeepmistry/arduino-LoRa.git
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306

; Build flags for ESP32
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -std=gnu++17

monitor_filters = esp32_exception_decoder
